name: 'benstepp/elixir-actions/mix-deps-compile'
author: 'Benjamin Stepp'
description: 'Compiles and Caches your application dependencies'

inputs:
  working-directory:
    description: 'Path to your elixir application. This can be configured if
      your elixir application is in a subdirectory, for example if you are in a
      monorepo.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Determine Information
      id: info
      shell: bash
      run: |
        if [[ "${{ inputs.working-directory }}" ]]; then cd ${{ inputs.working-directory }}; fi
        echo "::set-output name=elixir-version::$(mix hex.info | grep 'Elixir:' | sed -n 's/Elixir://p' | sed -n 's/\s//pg')"
        echo "::set-output name=otp-version::$(mix hex.info | grep 'OTP:' | sed -n 's/OTP://p' | sed -n 's/\s//pg')"
        echo "::set-output name=build-path::$(pwd)/_build_deps"
        echo "::set-output name=mix-lock-path::$(pwd)/mix.lock"

    - name: Cache Dependencies
      uses: actions/cache@v2
      id: cache-build-deps
      with:
        path: format('{0}/**', steps.info.outputs.build-path)
        key: ${{runner.os}}-${{runner.arch}}-${{ steps.info.outputs.elixir-version }}-${{ steps.info.outputs.otp-version }}-builddeps-${{ steps.info.outputs.build-path }}-${{ hashFiles( steps.info.outputs.mix-lock-path ) }}
        restore-keys: |
          ${{runner.os}}-${{runner.arch}}-${{ steps.info.outputs.elixir-version }}-${{ steps.info.outputs.otp-version }}-builddeps-${{ steps.info.outputs.build-path }}-

    - name: Compile Dependencies
      if: steps.cache-build-deps.outputs.cache-hit != 'true'
      shell: bash
      env:
        MIX_BUILD_ROOT: '_build_deps'
      run: |
        if [[ "${{ inputs.working-directory }}" ]]; then cd ${{ inputs.working-directory }}; fi
        mkdir -p _build_deps
        mix deps.compile

    - name: Merge _build directory
      shell: bash
      run: |
        if [[ "${{ inputs.working-directory }}" ]]; then cd ${{ inputs.working-directory }}; fi
        mkdir -p _build/
        rsync -a _build_deps/ _build
