name: 'benstepp/elixir-actions/mix-deps-compile'
author: 'Benjamin Stepp'
description: 'Compiles and Caches your application dependencies'

inputs:
  working-directory:
    description: 'Path to your elixir application. This can be configured if
      your elixir application is in a subdirectory, for example if you are in a
      monorepo.'
    required: false

runs:
  using: 'node16'
  main: './dist/index.js'
