name: 'mix deps.get'
description: 'Installs and caches your mix application dependencies.'
author: 'Benjamin Stepp'

inputs:
  working-directory:
    description: 'Path to your elixir application. This can be configured if
      your elixir application is in a subdirectory, for example if you are in a
      monorepo.'
    required: false

runs:
  using: 'node16'
  main: './dist/index.js'
