name: 'benstepp/elixir-actions/mix-compile'
author: 'Benjamin Stepp'
description: 'Compiles and Caches your application'

inputs:
  working-directory:
    description: 'Path to your elixir application. This can be configured if
      your elixir application is in a subdirectory, for example if you are in a
      monorepo.'
    required: false
  cache-key:
    description: 'Additional Cache Key to use in cache key generation.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Determine Information
      id: compile-info
      shell: bash
      run: |
        if [[ "${{ inputs.working-directory }}" ]]; then cd ${{ inputs.working-directory }}; fi
        echo "::set-output name=elixir-version::$(mix hex.info | grep 'Elixir:' | sed -n 's/Elixir://p' | sed -n 's/\s//pg')"
        echo "::set-output name=otp-version::$(mix hex.info | grep 'OTP:' | sed -n 's/OTP://p' | sed -n 's/\s//pg')"
        bash ${{ github.action_path }}/config-files.sh
        if [[ "${{ inputs.working-directory }}" ]]; then
          echo "::set-output name=app-path::${{ inputs.working-directory }}/**/*.ex"
          echo "::set-output name=src-path::${{ inputs.working-directory }}/**/*.erl"
          echo "::set-output name=build-path::${{ inputs.working-directory }}/_build_app"
          echo "::set-output name=include-path::${{ inputs.working-directory }}/include/**"
          echo "::set-output name=mix-lock-path::${{ inputs.working-directory }}/mix.lock"
          echo "::set-output name=priv-path::${{ inputs.working-directory }}/priv/**"
        else
          echo "::set-output name=app-path::**/*.ex"
          echo "::set-output name=src-path::**/*.erl"
          echo "::set-output name=build-path::_build_app"
          echo "::set-output name=include-path::include/**"
          echo "::set-output name=mix-lock-path::mix.lock"
          echo "::set-output name=priv-path::priv/**"
        fi

    - name: Cache Compiled App
      uses: actions/cache@v2
      id: cache-build-app
      with:
        path: ${{ steps.compile-info.outputs.build-path }}
        key: ${{runner.os}}-${{runner.arch}}-${{ steps.compile-info.outputs.elixir-version }}-${{ steps.compile-info.outputs.otp-version }}-buildapp-${{ steps.compile-info.outputs.build-path }}-${{ env.MIX_ENV }}-${{ hashFiles(fromJSON(steps.compile-info.outputs.config-files)) }}-${{ inputs.cache-key }}-${{ hashFiles( steps.compile-info.outputs.mix-lock-path ) }}-${{ hashFiles( steps.compile-info.outputs.app-path, steps.compile-info.outputs.src-path, steps.compile-info.outputs.include-path, steps.compile-info.outputs.priv-path ) }}
        restore-keys: |
          ${{runner.os}}-${{runner.arch}}-${{ steps.compile-info.outputs.elixir-version }}-${{ steps.compile-info.outputs.otp-version }}-buildapp-${{ steps.compile-info.outputs.build-path }}-${{ env.MIX_ENV }}-${{ hashFiles(fromJSON(steps.compile-info.outputs.config-files)) }}-${{ inputs.cache-key }}-${{ hashFiles( steps.compile-info.outputs.mix-lock-path ) }}-
          ${{runner.os}}-${{runner.arch}}-${{ steps.compile-info.outputs.elixir-version }}-${{ steps.compile-info.outputs.otp-version }}-buildapp-${{ steps.compile-info.outputs.build-path }}-${{ env.MIX_ENV }}-${{ hashFiles(fromJSON(steps.compile-info.outputs.config-files)) }}-${{ inputs.cache-key }}-
          ${{runner.os}}-${{runner.arch}}-${{ steps.compile-info.outputs.elixir-version }}-${{ steps.compile-info.outputs.otp-version }}-buildapp-${{ steps.compile-info.outputs.build-path }}-${{ env.MIX_ENV }}-${{ hashFiles(fromJSON(steps.compile-info.outputs.config-files)) }}-
          ${{runner.os}}-${{runner.arch}}-${{ steps.compile-info.outputs.elixir-version }}-${{ steps.compile-info.outputs.otp-version }}-buildapp-${{ steps.compile-info.outputs.build-path }}-${{ env.MIX_ENV }}-

          ${{runner.os}}-${{runner.arch}}-${{ steps.compile-info.outputs.elixir-version }}-${{ steps.compile-info.outputs.otp-version }}-buildapp-

    - name: Compile Application
      if: steps.cache-build-app.outputs.cache-hit != 'true'
      shell: bash
      env:
        MIX_BUILD_ROOT: '_build_app'
      run: |
        if [[ "${{ inputs.working-directory }}" ]]; then cd ${{ inputs.working-directory }}; fi
        mkdir -p _build_app
        rsync -a _build/ _build_app
        mix compile
        rsync -a --ignore-non-existing --remove-source-files _build_app/ _build

    - name: Merge _build directory
      shell: bash
      run: |
        if [[ "${{ inputs.working-directory }}" ]]; then cd ${{ inputs.working-directory }}; fi
        mkdir -p _build/
        rsync -a _build_app/ _build
