name: 'benstepp/elixir-actions/mix-deps-get'
author: 'Benjamin Stepp'
description: 'Installs and Caches your application dependencies'

inputs:
  working-directory:
    description: 'Path to your elixir application. This can be configured if
      your elixir application is in a subdirectory, for example if you are in a
      monorepo.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Determine Information
      id: info
      shell: bash
      run: |
        if [[ "${{ inputs.working-directory }}" ]]; then cd ${{ inputs.working-directory }}; fi
        echo "::set-output name=elixir-version::$(mix hex.info | grep 'Elixir:' | sed -n 's/Elixir://p' | sed -n 's/\s//pg')"
        echo "::set-output name=otp-version::$(mix hex.info | grep 'OTP:' | sed -n 's/OTP://p' | sed -n 's/\s//pg')"
        echo "::set-output name=deps-path::$(mix run -e 'Logger.remove_backend(:console);IO.inspect(Mix.Project.deps_path())' --no-archives-check --no-compile --no-deps-check --no-elixir-version-check --no-start | sed -n 's/\"//pg')"
        echo "::set-output name=mix-lock-path::$(pwd)/mix.lock"

    - name: Cache Dependencies
      uses: actions/cache@v2
      id: cache-deps
      with:
        path: format('{0}/**', steps.info.outputs.deps-path)
        key: ${{runner.os}}-${{runner.arch}}-${{ steps.info.outputs.elixir-version }}-${{ steps.info.outputs.otp-version }}-deps-${{ steps.info.outputs.deps-path }}-${{ hashFiles( steps.info.outputs.mix-lock-path ) }}
        restore-keys: |
          ${{runner.os}}-${{runner.arch}}-${{ steps.info.outputs.elixir-version }}-${{ steps.info.outputs.otp-version }}-deps-${{ steps.info.outputs.deps-path }}-

    - name: Install Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      shell: bash
      run: |
        if [[ "${{ inputs.working-directory }}" ]]; then cd ${{ inputs.working-directory }}; fi
        mix deps.get
