name: 'mix compile'
description: 'Compiles and caches your mix application.'
author: 'Benjamin Stepp'

inputs:
  cache-key:
    description: 'If your application has other files that affect the cache you
      can add a hash of them here. Can also be passed to "bust" the current cache.'
    required: false
    default: 'key'
  working-directory:
    description: 'Path to your elixir application. This can be configured if
      your elixir application is in a subdirectory, for example if you are in a
      monorepo.'
    required: false

runs:
  using: 'node16'
  main: './dist/index.js'
