name: Build Actions

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build Packaged Actions
        run: |
          npm run build:all

      - name: Prepare Output
        run: |
          cp README.md ./actions
          cp LICENSE ./actions

      - name: Push Build
        uses: s0/git-publish-subdir-action@v2.5.1
        env:
          REPO: self
          BRANCH: build
          FOLDER: actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
