name: 'CI'

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  setup:
    name: 'Setup Node.js'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'actions/setup-node@v3'
        with:
          node-version: '16'
          cache: 'npm'

      - name: 'npm ci'
        run: 'npm ci'

  format:
    name: 'prettier'
    runs-on: 'ubuntu-latest'
    needs: ['setup']
    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'actions/setup-node@v3'
        with:
          node-version: '16'
          cache: 'npm'

      - name: 'npm ci'
        run: 'npm ci'

      - name: 'npm run format:check'
        run: 'npm run format:check'

  lint:
    name: 'eslint'
    runs-on: 'ubuntu-latest'
    needs: ['setup']
    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'actions/setup-node@v3'
        with:
          node-version: '16'
          cache: 'npm'

      - name: 'npm ci'
        run: 'npm ci'

      - name: 'npm run lint'
        run: 'npm run lint'

  test:
    name: 'jest'
    runs-on: 'ubuntu-latest'
    needs: ['setup']
    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'actions/setup-node@v3'
        with:
          node-version: '16'
          cache: 'npm'

      - name: 'npm ci'
        run: 'npm ci'

      - name: 'npm run test'
        run: 'npm run test'

  build:
    name: 'build'
    runs-on: 'ubuntu-latest'
    needs: ['format', 'lint', 'test']
    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'actions/setup-node@v3'
        with:
          node-version: '16'
          cache: 'npm'

      - name: 'npm ci'
        run: 'npm ci'

      - name: 'npm run build:all'
        run: 'npm run build:all'

      - name: 'Prepare Output'
        if: ${{ github.event_name == 'push' }}
        run: |
          cp README.md ./actions
          echo ${{ github.ref }} >> ./actions/${{ github.sha }}
          sed -i 's/<!--AUTO-->/This was autogenerated. [Go to ex-actions\/ex-actions for the source](https:\/\/github.com\/ex-actions\/ex-actions)./' ./actions/README.md

      - name: 'Push Build'
        if: ${{ github.event_name == 'push' }}
        uses: 's0/git-publish-subdir-action@v2.5.1'
        env:
          REPO: 'self'
          BRANCH: 'build'
          FOLDER: 'actions'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
