name: Test - Elixir Umbrella Changes

on:
  workflow_dispatch:

env:
  working-directory: 'test_apps/test_umbrella'
  elixir-version: "1.14.0"
  otp-version: "25.0.4"
  MIX_ENV: test

defaults:
  run:
    working-directory: 'test_apps/test_umbrella'
    shell: bash

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: "./setup"
        with:
          working-directory: ${{ env.working-directory }}

  matrix:
    name: Change Apps Matrix
    needs: [compile]
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.changes.apps }}
    steps:
      - uses: actions/checkout@v2

      - uses: "./setup"
        with:
          working-directory: ${{ env.working-directory }}

      - uses: './umbrella-changes-matrix'
        id: changes
        with:
          working-directory: ${{ env.working-directory }}

  format:
    name: Format
    needs: [compile]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: "./setup"
        with:
          working-directory: ${{ env.working-directory }}

      - name: 'mix format'
        run: 'mix format --check-formatted'


  test:
    name: Test
    needs: [compile, matrix]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: ${{ fromJSON(needs.matrix.outputs.apps) }}

    steps:
      - uses: actions/checkout@v2

      - uses: "./setup"
        with:
          working-directory: ${{ env.working-directory }}

      - name: mix test ${{ matrix.app }}

        run: |
          cd ${{ env.working-directory }}
          echo "${{ matrix.app }}"
          mix cmd --app ${{ matrix.app }} mix test --color

  lol:
    name: Test
    needs: [compile, matrix]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: "./setup"
        with:
          working-directory: ${{ env.working-directory }}

      - name: lol
        run: |
          echo "${{ needs.matrix.outputs.apps }}"
          echo "${{ toJSON(needs.matrix.outputs) }}"
